Fix unused import error in integration tests
> error: unused import: `std::env`
>   --> cargo-geiger/tests/integration_tests.rs:11:5
>    |
> 11 | use std::env;
>    |     ^^^^^^^^
>    |
> note: the lint level is defined here
>   --> cargo-geiger/tests/integration_tests.rs:2:11
>    |
>  2 | #![forbid(warnings)]
>    |           ^^^^^^^^
>    = note: `#[forbid(unused_imports)]` implied by `#[forbid(warnings)]`
>
> error: could not compile `cargo-geiger` (test "integration_tests") due to 1 previous error