Update to work with Rust 1.85 (#518)
* Undo recent cargo_metadata dependency update which broke the build.

* Update a dep version in test snapshot file.  Tests pass with Rust 1.74.

* Support Rust 1.76: Fix tests broken by cargo metadata format change.

* Migrate to `syn` v2 to fix crashes when parsing Rust 1.77 code with C-string literals `c""` https://doc.rust-lang.org/edition-guide/rust-2021/c-string-literals.html : thread '<unnamed>' panicked at /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/syn-1.0.109/src/lit.rs:1020:13: Unrecognized literal: `c""`

* CI to use Rust 1.76.  This is necessary until we migrate to `cargo_metadata` v18.

* Build under Rust 1.77: Fix error field `0` is never read

* Switch tests from itertools 0.8.0 to 0.12.1, to fix crash: Failed to parse file: /Users/user/.cargo/git/checkouts/itertools-eb89fd56766bcf43/8761fbe/src/format.rs, Syn(Error("expected ','").

* Update test snapshot with new version of `either` dep.

* Update expected values for serialize_test*_report tests.  Also make the output of SafetyReport assert_eq failures comparable.

* Build with Rust 1.85.

* Set MSRV.

* rustfmt.

* Clarify some comments.